databases:
  - name: myblogdb
    plan: free
    databaseName: myblogdb
    user: userweb

services:
  - type: web
    plan: free
    name: myblog
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn myblog.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: myblogdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4